// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// c_hat
arma::mat c_hat(arma::mat E0, arma::mat F0, arma::colvec cy);
RcppExport SEXP _fda2d_c_hat(SEXP E0SEXP, SEXP F0SEXP, SEXP cySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type E0(E0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type F0(F0SEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type cy(cySEXP);
    rcpp_result_gen = Rcpp::wrap(c_hat(E0, F0, cy));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fda2d_c_hat", (DL_FUNC) &_fda2d_c_hat, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_fda2d(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
