# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @importFrom Rcpp sourceCpp
#' @useDynLib fda2d
#' @export
c_hat <- function(E0, F0, cy) {
    .Call('_fda2d_c_hat', PACKAGE = 'fda2d', E0, F0, cy)
}

